### ISSUE TITLE
Change category selection in cat gallery to entire p-card

### ISSUE THREAD

**Issue by charchow** [Open-Source-Medical-Supplies/react-categories-gallery#5]
eliminate view button/change category selection to entire card; maybe change color upon mouseover/hover to indicate actionability and/or on mouseclick; similar to Kimly's wish for these category tiles to take up less space/reduce white space

Name: Gui Cavalcanti
Date: 6/10/2020
Browser: Chrome
Issue: Would it be possible to change this so the entire square category depiction is the link, instead of a ‘view’ button - so you just hover over the category you want and click it?
Page / Location: Category Library
![cat library tile view](https://user-images.githubusercontent.com/63361740/84536068-10dcf780-acbb-11ea-8e69-01f9f292cd7b.png)

**Comment by JoshMLeslie** [comment]
Hovering is not a valid interaction on mobile but I can make the cards smaller / open to other suggestions
